services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: utilisateur-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_identity_flow:5432/vendredi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8082:8082"
    networks:
      - app-network
networks:
  app-network: