services:
  database:
    image: postgres:15-alpine
    container_name: cryptomonnaie-database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: phoenix_coin
    ports:
      - "5434:5432"
    volumes:
      - identity-flow_postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cryptomonnaie-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cryptomonnaie-database:5432/phoenix_coin
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8080
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: gestionsender@gmail.com
      SPRING_MAIL_PASSWORD: crgyvlhzmezpqdkc
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  identity-flow_postgres_data:
    external: true  # Indique que le volume existe déjà